[tools]
java = "openjdk-17"
neovim = "latest"
rg = "latest"
fd = "latest"
tmux = "latest"
fzf = "latest"
tree-sitter = "latest"
sbt = "latest"
coursier = "latest"

go = "latest"
gomplate = "latest"

jq = "latest"
yq = "latest"

git-lfs = "latest"

[settings]
experimental = true
lockfile = true
