export EDITOR=nvim
alias sudo='sudo '
alias l='ls'
alias la='exa -a -s type'
alias ll='exa -llh -s type'
alias lla='exa -llah -s type'
alias lai='exa -a -s type --icons'
alias lli='exa -llh -s type --icons'
alias llai='exa -llah -s type --icons'
alias tree='exa -T'
alias rm='rm -i'
alias vi='nvim'
alias vim='nvim'
alias open='xdg-open'

