live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#3b8eea"
cyan = "#29b8db"
green = "#23d18b"
magenta = "#d670d6"
red = "#f14c4c"
white = "#e5e5e5"
yellow = "#f5f543"

[colors.normal]
black = "#000000"
blue = "#2472c8"
cyan = "#11a8cd"
green = "#0dbc79"
magenta = "#bc3fbc"
red = "#cd3131"
white = "#e5e5e5"
yellow = "#e5e510"

[colors.primary]
background = "#262626"

[cursor]
thickness = 0.15
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "NotoSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "NotoSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "NotoSansM Nerd Font"
style = "Italic"

[font.normal]
family = "NotoSansM Nerd Font"
style = "Medium"

[font.offset]
x = -1
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[scrolling]
history = 1000
multiplier = 3

[shell]
args = ["--login", "-c", "which tmux &> /dev/null && { tmux attach || tmux; } || zsh"]
program = "zsh"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"
opacity = 0.999
dimensions = { columns = 160, lines = 40 }
padding = { x = 4, y = 1 }

